import React from 'react';

const EFFECTIVE = 'May 1, 2025';

export default function AIUsagePolicy() {
  return (
    <div className="min-h-screen bg-[#06060e] text-foreground">
      <div className="max-w-3xl mx-auto px-6 py-16">

        <div className="mb-10">
          <span className="text-xs font-semibold uppercase tracking-widest text-violet-400">Legal</span>
          <h1 className="text-4xl font-black mt-2 mb-3">AI Usage Policy</h1>
          <p className="text-sm text-muted-foreground">Effective date: {EFFECTIVE}</p>
        </div>

        <div className="bg-amber-500/8 border border-amber-500/20 rounded-2xl p-5 mb-10">
          <p className="text-sm text-amber-300/80 leading-relaxed">
            <strong className="text-amber-300">Sound2Soul's foundational principle:</strong> Creators using AI tools
            are welcomed and celebrated here — but only when they are honest about it. This policy defines how AI
            disclosure works and what responsibilities creators carry.
          </p>
        </div>

        <Prose>
          <H2>1. Scope</H2>
          <p>
            This AI Usage Policy applies to all music, artwork, Soul Stories, and other content published on Sound2Soul
            by creators. It supplements the Terms of Service and Creator Guidelines.
          </p>

          <H2>2. What Is "AI-Assisted" Content?</H2>
          <p>
            Any content where an AI tool contributed meaningfully to the creative output is considered AI-assisted. This
            includes but is not limited to:
          </p>
          <ul>
            <li>Audio generated in full or in part by tools such as Suno, Udio, MusicGen, or similar;</li>
            <li>Vocals, instrumentation, or arrangements produced or substantially modified by AI;</li>
            <li>Cover art or visual assets generated by image-synthesis tools (Midjourney, DALL-E, etc.);</li>
            <li>Lyrics written or substantially revised by large language models;</li>
            <li>Soul Stories or track descriptions ghost-written by AI without meaningful human editing.</li>
          </ul>

          <H2>3. Mandatory Disclosure</H2>
          <p>
            Every creator must accurately complete the AI disclosure section when uploading a track. Sound2Soul
            recognises the following disclosure levels:
          </p>
          <ul>
            <li>
              <strong>Human-created, no AI:</strong> All creative decisions, audio, and lyrics were produced entirely
              by human effort. No AI tools were used.
            </li>
            <li>
              <strong>AI-assisted:</strong> AI contributed to some aspects (e.g., mastering, mixing suggestions,
              lyric brainstorming) but the core creative direction was human-led.
            </li>
            <li>
              <strong>Primarily AI-generated:</strong> AI tools produced the majority of the audio or creative
              content. Human contribution was curatorial, directional, or editorial.
            </li>
            <li>
              <strong>Fully AI-generated:</strong> The track was produced entirely by AI with minimal or no human
              creative input beyond the prompt.
            </li>
          </ul>

          <H2>4. Prohibited Conduct</H2>
          <p>The following are strictly prohibited and constitute grounds for immediate account termination:</p>
          <ul>
            <li>Falsely claiming a track is "human-created" when AI tools produced it;</li>
            <li>Misrepresenting the disclosure level (e.g., selecting "AI-assisted" for fully AI-generated work);</li>
            <li>Using AI to clone, replicate, or impersonate the voice or style of an identifiable living artist
              without their documented consent;</li>
            <li>Training AI models on other creators' Sound2Soul content without explicit written consent;</li>
            <li>Publishing AI-generated content that violates the rights of any third party.</li>
          </ul>

          <H2>5. Rights & Ownership of AI Content</H2>
          <p>
            Sound2Soul does not adjudicate copyright ownership of AI-generated content. By publishing AI-assisted
            content, you represent and warrant that:
          </p>
          <ul>
            <li>You have reviewed and comply with the terms of service of any AI tool you used;</li>
            <li>You have not used any unauthorised training data or copyrighted samples;</li>
            <li>You accept full personal responsibility for any intellectual property claims arising from your content.</li>
          </ul>
          <p>
            Sound2Soul's Rights Certification is a creator self-certification only. It does not constitute legal
            clearance or a warranty of copyright ownership from Sound2Soul.
          </p>

          <H2>6. Moderation of AI Content</H2>
          <p>
            Our moderation team reviews all flagged content. Tracks suspected of misrepresentation may be:
          </p>
          <ul>
            <li>Temporarily unlisted pending creator review;</li>
            <li>Permanently removed from the platform;</li>
            <li>Subject to account suspension or termination.</li>
          </ul>
          <p>
            Creators may appeal moderation decisions by contacting{' '}
            <a href="mailto:moderation@sound2soul.com" className="text-violet-400 hover:underline">moderation@sound2soul.com</a> within 14 days.
          </p>

          <H2>7. Soul Score & AI Content</H2>
          <p>
            All tracks — regardless of AI involvement level — contribute equally to Soul Score calculations.
            Sound2Soul does not penalise creators for using AI tools. We reward transparency.
          </p>

          <H2>8. Policy Updates</H2>
          <p>
            The AI landscape evolves rapidly. We will update this policy as needed and notify creators of material
            changes. Your continued use of the platform following an update constitutes acceptance.
          </p>

          <H2>9. Contact</H2>
          <p>
            Questions about AI disclosure or this policy? Email{' '}
            <a href="mailto:ai-policy@sound2soul.com" className="text-violet-400 hover:underline">ai-policy@sound2soul.com</a>.
          </p>
        </Prose>
      </div>
    </div>
  );
}

function H2({ children }: { children: React.ReactNode }) {
  return <h2 className="text-xl font-bold mt-10 mb-3 text-white">{children}</h2>;
}

function Prose({ children }: { children: React.ReactNode }) {
  return (
    <div className="space-y-5 text-muted-foreground leading-relaxed text-[15px] [&_ul]:list-disc [&_ul]:pl-5 [&_ul]:space-y-2 [&_strong]:text-white [&_p]:text-muted-foreground">
      {children}
    </div>
  );
}
